Add course level redirects when access is unauthoriized
freshbrewedweb/wp-classroom pull request #19
Opened 2019-07-26 07:28 UTC by jpaulcrosby

2019-07-26 18:01 UTC, greghunt requested changes

2019-07-26 18:01 UTC, greghunt commented on admin/class-wp-classroom-admin.php
> +			'course_redirect'            => __( 'No access to course', 'wp-classroom')
@jpaulcrosby what's this for? It's not an option in the expected labels:
https://developer.wordpress.org/reference/functions/get_taxonomy_labels/

2019-07-26 18:01 UTC, greghunt commented on admin/class-wp-classroom-admin.php
> +			'taxonomies'  => array( 'wp_course' ),
this should use term_meta as well, shouldn't it?

2019-07-26 18:01 UTC, greghunt commented on includes/class-wp-classroom-users.php
> +        $course_id = $all_terms->parent ? $all_terms->parent : $all_terms->term_id;
Why are we using get_taxonomies() ? This is only applicable to `wp_course`. Also, we're only checking the first term for some reason. There should probably be a loop somewhere to check presence of redirect on each term this class has.

2019-07-26 18:18 UTC, jpaulcrosby commented on admin/class-wp-classroom-admin.php
> +			'course_redirect'            => __( 'No access to course', 'wp-classroom')
You are totally right. We can delete this. Ill resubmit on this one.

2019-07-29 14:04 UTC, greghunt approved these changes

2019-07-29 14:04 UTC, merged